# Generated by Django 4.0.2 on 2022-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oreder_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=5000)),
                ('city', models.CharField(default='', max_length=5000)),
                ('zip_code', models.CharField(default='', max_length=5000)),
                ('state', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
