# Generated by Django 4.0.2 on 2022-02-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='oreder_id',
            new_name='order_id',
        ),
    ]
